---
deployment:
  tasks:
    - export DEPLOYPATH=/home/supremeb/rukmagatkandel.com.np/wp-content/themes/wpdev-portfolio/
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R inc $DEPLOYPATH
    - /bin/cp -R template-parts $DEPLOYPATH
    - /bin/cp *.php $DEPLOYPATH
